# spring config server
server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SamsaraCloud/microservicecloud-config.git  # githup 上 git 仓库
          username: SamsaraCloud
          password: yyzl2840032159
